<!--This is a machine created file.
 Do not edit. Edit getAliases and run like:
 php getAliases.php > searchvars.php
--><?php 
 $all_attributes = array( 
 't_psfmagerr_r' => array('type' => 'numeric', 'name' => 't psfmagerr r', 'description' => ''), 
 'twomassmagerr_j' => array('type' => 'numeric', 'name' => 'Jerr', 'description' => '2MASS J magnitude error                    ** Note that 2MASS measurements are Vega-based, not AB, magnitudes **'), 
 'oldname_type' => array('type' => 'numeric', 'name' => 'oldname type', 'description' => ''), 
 'z_best' => array('type' => 'numeric', 'name' => 'z qso (best)', 'description' => 'Best determined emission redshift, used by the pipeline (from Hewett & Wild 2010, if available)'), 
 'psfmag_i' => array('type' => 'numeric', 'name' => 'i', 'description' => ''), 
 'w_limit_1549_1909' => array('type' => 'numeric', 'name' => 'W limit 1549-1909', 'description' => 'W limit (median two pixel 1-sigma error) between restframe [1549.48-1908.73]'), 
 'ts_b_rosat' => array('type' => 'bool', 'name' => 'ts b rosat', 'description' => 'ROSAT target flag           0 = not targeted as ROSAT        1 = targeted as ROSAT'), 
 'ra' => array('type' => 'numeric', 'name' => 'ra', 'description' => ''), 
 'bestprimtarget' => array('type' => 'bool', 'name' => 'bestprimtarget', 'description' => ''), 
 'qso_bal_flag2' => array('type' => 'numeric', 'name' => 'qso bal flag2', 'description' => 'Broad Absorption Line System QSO flag from Shen et al. DR7 BAL Catalog 0 = not identified as a BALQSO 1 = BAL identified in DR5 Gibson et al. catalog  2 = BAL candidate identified by Shen only  3 = BAL identified by Wesolowski only  4 = BAL candidate identified by both Shen and Wesolowski'), 
 'qso_spec_avesnr' => array('type' => 'numeric', 'name' => 'qso spec avesnr', 'description' => 'Mean per-pixel SNR of the spectrum at lambda>1250 Angstroms in the quasar rest frame'), 
 'agg_line_w_rest' => array('type' => 'similar', 'name' => 'agg line W rest', 'description' => ''), 
 'sys_type' => array('type' => 'numeric', 'name' => 'sys type', 'description' => 'Selection method for identifying system - some combination of M;C; and F'), 
 'psfmag_u' => array('type' => 'numeric', 'name' => 'u', 'description' => 'u PSF magnitude'), 
 'psfmagerr_z' => array('type' => 'numeric', 'name' => 'zErr', 'description' => 'z PSF magnitude error'), 
 'ts_b_gal' => array('type' => 'bool', 'name' => 'ts b gal', 'description' => ''), 
 't_psfmagerr_g' => array('type' => 'numeric', 'name' => 't psfmagerr g', 'description' => ''), 
 'agg_line_obs_lam' => array('type' => 'similar', 'name' => 'agg line obs lam', 'description' => ''), 
 'oldname_desig' => array('type' => 'numeric', 'name' => 'oldname desig', 'description' => 'Object Name if previously published.'), 
 'qso_w_limit_3969_8200' => array('type' => 'numeric', 'name' => 'qso W limit 3969-8200', 'description' => ''), 
 'twomassmag_k' => array('type' => 'numeric', 'name' => 'K', 'description' => '2MASS K magnitude'), 
 'w_limit_2799_3969' => array('type' => 'numeric', 'name' => 'W limit 2799-3969', 'description' => 'W limit (median two pixel 1-sigma error) between restframe [2799.117-3969.0]'), 
 'qso_w_limit_1216_1241' => array('type' => 'numeric', 'name' => 'qso W limit 1216-1241', 'description' => ''), 
 'agg_line_deltaz' => array('type' => 'similar', 'name' => 'agg line deltaz', 'description' => ''), 
 'psfmag_u' => array('type' => 'numeric', 'name' => 'u', 'description' => ''), 
 'lgnh' => array('type' => 'numeric', 'name' => 'log[n_h]', 'description' => ''), 
 'obs_lam' => array('type' => 'numeric', 'name' => 'obs lam', 'description' => 'Observed Wavelength: observed wavelength of the absorption line in Angstroms'), 
 'psfmagerr_g' => array('type' => 'numeric', 'name' => 'gErr', 'description' => 'g PSF magnitude error'), 
 'qso_w_limit_1241_1400' => array('type' => 'numeric', 'name' => 'qso W limit 1241-1400', 'description' => ''), 
 'fiber' => array('type' => 'numeric', 'name' => 'fiber', 'description' => ''), 
 'agg_lid' => array('type' => 'similar', 'name' => 'agg lid', 'description' => ''), 
 'line_w_obserr' => array('type' => 'numeric', 'name' => 'line Wobserr', 'description' => '1-sigma error (in Angstroms) on the observer-frame equivalent width'), 
 't_psfmagerr_i' => array('type' => 'numeric', 'name' => 't psfmagerr i', 'description' => ''), 
 'twomassmag_j' => array('type' => 'numeric', 'name' => 'J', 'description' => '2MASS J magnitude          All 2MASS data are from the 2MASS All-Sky Data Release  Point Source Catalog (PSC)   2003 March 25      0.000 ==> no detection'), 
 'redshift' => array('type' => 'numeric', 'name' => 'z QSO', 'description' => 'Redshift'), 
 'first_sn' => array('type' => 'numeric', 'name' => 'first_sn', 'description' => ''), 
 'delgi' => array('type' => 'numeric', 'name' => 'delta(g-i)', 'description' => 'Delta(g-i)  Offset in magnitudes of the quasar (g-i) from the mode of the distribution of (g-i) of quasars at this redshift.  A value of -9.0 indicates too few quasars at redshift to form mean relation.  (All colors corrected for Galactic extinction)'), 
 'twomassmagerr_h' => array('type' => 'numeric', 'name' => 'Herr', 'description' => '2MASS H magnitude error'), 
 'w_limit_3969_8200' => array('type' => 'numeric', 'name' => 'W limit 396- 8200', 'description' => 'W limit (median two pixel 1-sigma error) between restframe [3969.0-8200.0]'), 
 'psfmagerr_i' => array('type' => 'numeric', 'name' => 'iErr', 'description' => ''), 
 'twomassmag_h' => array('type' => 'numeric', 'name' => 'H', 'description' => ''), 
 'twomassmag_k' => array('type' => 'numeric', 'name' => 'K', 'description' => ''), 
 'qso_w_limit_3969_8200' => array('type' => 'numeric', 'name' => 'qso W limit 3969-8200', 'description' => 'W limit (median two pixel 1-sigma error) between restframe [3969.0-8200.0]'), 
 'sid' => array('type' => 'numeric', 'name' => 'sysId', 'description' => 'system id (incremented for each system)'), 
 'morphology' => array('type' => 'bool', 'name' => 'morphology', 'description' => 'Morphology flag            0 = point source      1 = extended'), 
 'imag' => array('type' => 'numeric', 'name' => 'imag', 'description' => ''), 
 'camcol_best' => array('type' => 'numeric', 'name' => 'camcol best', 'description' => 'SDSS Camera Column Number'), 
 'run_best' => array('type' => 'numeric', 'name' => 'run best', 'description' => ''), 
 'geopoint' => array('type' => 'numeric', 'name' => 'geopoint', 'description' => 'Binary representation of lon/lat for spatial queries'), 
 'sys_beta' => array('type' => 'numeric', 'name' => 'sys beta', 'description' => ''), 
 'ts_t_serendip' => array('type' => 'bool', 'name' => 'ts t serendip', 'description' => 'Serendipity target flag     0 = not targeted as serendipity  1 = targeted as serendipity'), 
 'twomass_flag' => array('type' => 'numeric', 'name' => '2MASS flag', 'description' => ''), 
 'lon' => array('type' => 'numeric', 'name' => 'lon', 'description' => ''), 
 'qso_z_fgal' => array('type' => 'numeric', 'name' => 'qso z fgal', 'description' => 'Redshift of identified foreground galaxy'), 
 'oldname_desig' => array('type' => 'numeric', 'name' => 'oldname desig', 'description' => 'Object Name Prefix if previously published. (SDSS in this column indicates that the object is a previously published SDSS discovery)'), 
 'a_u' => array('type' => 'numeric', 'name' => 'A_u', 'description' => 'Galactic absorption in u band (magnitudes) A_g, A_r, A_i, A_z = 0.736, 0.534, 0.405, 0.287 x A_u'), 
 'balcode' => array('type' => 'numeric', 'name' => 'balcode', 'description' => 'BAL flag (from Shen et al. 2011, ApJS, 194, 45). 0=nonBALQSO or no wavelength coverage; 1=CIV BALQSO; 2=MgII BALQSO; 3=both CIV and MgII BALQSO'), 
 'twomassmagerr_k' => array('type' => 'numeric', 'name' => 'Kerr', 'description' => '2MASS K magnitude error'), 
 'scienceprimary' => array('type' => 'numeric', 'name' => 'scienceprimary', 'description' => 'SCIENCEPRIMARY flag        0 = Object is not SCIENCEPRIMARY       1 = Object is SCIENCEPRIMARY'), 
 'lg_rass_rate' => array('type' => 'numeric', 'name' => 'lg_rass_rate', 'description' => 'log RASS BSC/FSC full band count rate (counts/second)     -9.000 ==> no detection          X-ray data from ROSAT All Sky Survey  Bright and Faint source catalogs'), 
 'ion_lam' => array('type' => 'categorical', 'name' => 'ion lam', 'description' => 'Laboratory wavelength of transition (Angstroms)'), 
 'ts_b_gal' => array('type' => 'bool', 'name' => 'ts b gal', 'description' => 'Galaxy target flag          0 = not targeted as galaxy       1 = targeted as galaxy'), 
 'z' => array('type' => 'numeric', 'name' => 'z', 'description' => 'QSO redshift (Schneider et al. 2010)'), 
 'obj_best' => array('type' => 'numeric', 'name' => 'obj best', 'description' => ''), 
 'ts_b_serendip' => array('type' => 'bool', 'name' => 'ts b serendip', 'description' => ''), 
 'qso_bal_flag' => array('type' => 'numeric', 'name' => 'qso bal flag', 'description' => ''), 
 'qso_w_limit_2799_3969' => array('type' => 'numeric', 'name' => 'qso W limit 2799-3969', 'description' => 'W limit (median two pixel 1-sigma error) between restframe [2799.117-3969.0]'), 
 'targprimtarget' => array('type' => 'numeric', 'name' => 'targprimtarget', 'description' => 'Target selection flag (TARGET)'), 
 't_psfmagerr_z' => array('type' => 'numeric', 'name' => 't psfmagerr z', 'description' => 'error in z PSF magnitude (TARGET)'), 
 'ra' => array('type' => 'numeric', 'name' => 'ra', 'description' => 'R.A.(J2000) in degrees'), 
 'sys_zab' => array('type' => 'numeric', 'name' => 'sys zab', 'description' => ''), 
 't_psfmag_z' => array('type' => 'numeric', 'name' => 't psfmag z', 'description' => ''), 
 'fiber' => array('type' => 'numeric', 'name' => 'fiber', 'description' => 'Spectroscopic fiber number'), 
 'targprimtarget' => array('type' => 'numeric', 'name' => 'targprimtarget', 'description' => ''), 
 'specid' => array('type' => 'numeric', 'name' => 'specid', 'description' => ''), 
 'auth_srid' => array('type' => 'numeric', 'name' => 'auth_srid', 'description' => ''), 
 'first_sep' => array('type' => 'numeric', 'name' => 'first_sep', 'description' => 'SDSS/FIRST separation (arc seconds)'), 
 'm_i' => array('type' => 'numeric', 'name' => 'M_i', 'description' => 'M_i  (Absolute i magnitude for Ho:  70.0     Omega_M:   0.300     Omega_L:   0.700     alpha_Q: -0.50)'), 
 'line_w_obs' => array('type' => 'numeric', 'name' => 'line Wobs', 'description' => 'Observer-frame equivalent width in Angstroms as determined by fitting a Gaussian profile to the absorption line'), 
 'uniform' => array('type' => 'numeric', 'name' => 'uniform', 'description' => 'Uniform target selection flag     (0 = not selected with final algorithm    1 = selected with final algorithm'), 
 'sep_first' => array('type' => 'numeric', 'name' => 'sep first', 'description' => 'Angular separation of SDSS/FIRST sources (arcsec) (Schneider et al. 2010)'), 
 't_psfmag_g' => array('type' => 'numeric', 'name' => 't psfmag g', 'description' => ''), 
 'arr_lid' => array('type' => 'similar', 'name' => 'arr lid', 'description' => ''), 
 'psfmag_z' => array('type' => 'numeric', 'name' => 'z', 'description' => ''), 
 'qso_w_limit_1400_1549' => array('type' => 'numeric', 'name' => 'qso W limit 1400-1549', 'description' => 'W limit (median two pixel 1-sigma error) between restframe [1399.8-1549.48]'), 
 'psfmag_r' => array('type' => 'numeric', 'name' => 'r', 'description' => 'r PSF magnitude'), 
 'qso_w_limit_1241_1400' => array('type' => 'numeric', 'name' => 'qso W limit 1241-1400', 'description' => 'W limit (median two pixel 1-sigma error) between restframe [1240.81-1399.8]'), 
 'spec_avesnr' => array('type' => 'numeric', 'name' => 'spec <SNR>', 'description' => 'Mean per-pixel SNR of the spectrum at lambda>1250 Angstroms in the quasar rest frame'), 
 'agg_line_ion_name' => array('type' => 'similar', 'name' => 'agg line ion name', 'description' => ''), 
 'morphology' => array('type' => 'bool', 'name' => 'morphology', 'description' => ''), 
 'ts_b_hiz' => array('type' => 'bool', 'name' => 'ts b hiz', 'description' => ''), 
 'twomassmag_j' => array('type' => 'numeric', 'name' => 'J', 'description' => ''), 
 'ts_b_star' => array('type' => 'bool', 'name' => 'ts b star', 'description' => 'Star target flag            0 = not targeted as star         1 = targeted as star'), 
 'qso_w_limit_2799_3969' => array('type' => 'numeric', 'name' => 'qso W limit 2799-3969', 'description' => ''), 
 'qso_w_limit_1216_1241' => array('type' => 'numeric', 'name' => 'qso W limit 1216-1241', 'description' => 'W limit (median two pixel 1-sigma error) between restframe [1215.7-1240.81'), 
 'bal_flag' => array('type' => 'numeric', 'name' => 'BAL flag', 'description' => 'Broad Absorption Line System QSO flag. 0 = not identified as a BALQSO 1 = BAL identified in DR5 Gibson et al. catalog 10 = BAL verified by DVB, in post-DR5 catalog 20 = BAL candidate inspected by DVB but of ambiguous classification, in post-DR5 catalog'), 
 'psfmagerr_z' => array('type' => 'numeric', 'name' => 'zErr', 'description' => ''), 
 'qso_spec_medsnr' => array('type' => 'numeric', 'name' => 'qso spec medsnr', 'description' => 'Median per-pixel SNR of the spectrum at lambda>1250 Angstroms in the quasar rest frame'), 
 'lam_low' => array('type' => 'numeric', 'name' => 'lam low', 'description' => 'Lower wavelength limit of the SDSS spectrograph in Angstroms in the absorber rest frame'), 
 'ts_t_first' => array('type' => 'bool', 'name' => 'ts t first', 'description' => 'FIRST target flag           0 = not targeted as FIRST        1 = targeted as FIRST'), 
 'first_sn' => array('type' => 'numeric', 'name' => 'first_sn', 'description' => 'S/N ratio for FIRST flux'), 
 'deltav' => array('type' => 'numeric', 'name' => 'deltav', 'description' => 'Velocity difference; determined from deltaz'), 
 'w_limit_1909_2799' => array('type' => 'numeric', 'name' => 'W limit 1909-2799', 'description' => 'W limit (median two pixel 1-sigma error) between restframe [1908.73-2799.117]'), 
 'psfmag_g' => array('type' => 'numeric', 'name' => 'g', 'description' => ''), 
 'sid' => array('type' => 'numeric', 'name' => 'sysId', 'description' => ''), 
 't_psfmagerr_u' => array('type' => 'numeric', 'name' => 't psfmagerr u', 'description' => ''), 
 'rass_sep' => array('type' => 'numeric', 'name' => 'rass_sep', 'description' => 'SDSS/RASS separation (arc seconds)'), 
 'z_s10' => array('type' => 'numeric', 'name' => 'z qso (S10)', 'description' => 'Emission redshift of the QSO from Schneider et al. 2010 DR7 QSO Catalog'), 
 'spec_avesnr_red' => array('type' => 'numeric', 'name' => 'spec <SNR> red', 'description' => 'Mean per-pixel SNR of the spectrum at lambda>7200 Angstroms in the observed frame'), 
 'agg_line_w_obs' => array('type' => 'similar', 'name' => 'agg line Wobs', 'description' => ''), 
 'line_ion_lam' => array('type' => 'categorical', 'name' => 'line ion lam', 'description' => 'Laboratory wavelength of transition (Angstroms)'), 
 'qso_agg_ab_sys' => array('type' => 'similar', 'name' => 'qso agg ab sys', 'description' => ''), 
 'qso_w_limit_1549_1909' => array('type' => 'numeric', 'name' => 'qso W limit 1549-1909', 'description' => ''), 
 'decl' => array('type' => 'numeric', 'name' => 'decl', 'description' => 'Dec.(J2000) in degrees'), 
 'agg_line_ly_a' => array('type' => 'similar', 'name' => 'agg line in lya forest', 'description' => ''), 
 'qso_bal_flag' => array('type' => 'numeric', 'name' => 'qso bal flag', 'description' => 'Broad Absorption Line System QSO flag. 0 = not identified as a BALQSO 1 = BAL identified in DR5 Gibson et al. catalog 10 = BAL verified by DVB, in post-DR5 catalog 20 = BAL candidate inspected by DVB but of ambiguous classification, in post-DR5 catalog'), 
 'decl' => array('type' => 'numeric', 'name' => 'decl', 'description' => ''), 
 'sys_type' => array('type' => 'numeric', 'name' => 'sys type', 'description' => ''), 
 'ts_t_lowz' => array('type' => 'bool', 'name' => 'ts t lowz', 'description' => ''), 
 'balcode' => array('type' => 'numeric', 'name' => 'balcode', 'description' => ''), 
 'srtext' => array('type' => 'numeric', 'name' => 'srtext', 'description' => ''), 
 'ts_t_star' => array('type' => 'bool', 'name' => 'ts t star', 'description' => 'Star target flag            0 = not targeted as star         1 = targeted as star'), 
 'line_fwhm' => array('type' => 'numeric', 'name' => 'line fwhm', 'description' => 'FWHM of the line (pixels)'), 
 't_psfmag_g' => array('type' => 'numeric', 'name' => 't psfmag g', 'description' => 'g PSF magnitude (TARGET)'), 
 'sid' => array('type' => 'numeric', 'name' => 'sysId', 'description' => 'System id (incremented for each system)'), 
 'ts_b_hiz' => array('type' => 'bool', 'name' => 'ts b hiz', 'description' => 'High-z Quasar (color selection only) target flag          0 = not targeted as high-z quasar       1 = targeted as high-z quasar'), 
 'lon' => array('type' => 'numeric', 'name' => 'lon', 'description' => ' R.A. (degrees) -180 < longitude < +180'), 
 'specid' => array('type' => 'numeric', 'name' => 'specid', 'description' => 'Spectrocopic id (primary key)'), 
 'plate' => array('type' => 'numeric', 'name' => 'plate', 'description' => 'Spectroscopic Plate Number'), 
 'sys_grade' => array('type' => 'numeric', 'name' => 'sys grade', 'description' => 'Confidence grade assigned to the absorption system'), 
 'rerun_best' => array('type' => 'numeric', 'name' => 'rerun best', 'description' => 'SDSS Photometric Processing Rerun Number'), 
 'ts_t_gal' => array('type' => 'bool', 'name' => 'ts t gal', 'description' => 'Galaxy target flag          0 = not targeted as galaxy       1 = targeted as galaxy'), 
 'qid' => array('type' => 'numeric', 'name' => 'QSOId', 'description' => 'QSO id (inremented for each qso)'), 
 'spec_medsnr' => array('type' => 'numeric', 'name' => 'spec median SNR', 'description' => 'Median per-pixel SNR of the spectrum at lambda>1250 Angstroms in the quasar rest frame'), 
 'qso_w_limit_1549_1909' => array('type' => 'numeric', 'name' => 'qso W limit 1549-1909', 'description' => 'W limit (median two pixel 1-sigma error) between restframe [1549.48-1908.73]'), 
 'sys_lam_low' => array('type' => 'numeric', 'name' => 'sys lam low', 'description' => 'Lower wavelength limit of the SDSS spectrograph in Angstroms in the absorber rest frame'), 
 'sys_lam_low' => array('type' => 'numeric', 'name' => 'sys lam low', 'description' => ''), 
 'redshift' => array('type' => 'numeric', 'name' => 'z QSO', 'description' => ''), 
 'ts_b_star' => array('type' => 'bool', 'name' => 'ts b star', 'description' => ''), 
 'grade' => array('type' => 'categorical', 'name' => 'grade', 'description' => 'Confidence grade assigned to the absorption system'), 
 'sys_beta' => array('type' => 'numeric', 'name' => 'sys beta', 'description' => 'Velocity (v/c) of the absorber in the QSO rest-frame; calculated using Hewett & Wild 2010 redshifts'), 
 'mode' => array('type' => 'numeric', 'name' => 'mode', 'description' => ''), 
 'qso_w_limit_1909_2799' => array('type' => 'numeric', 'name' => 'qso W limit 1909-2799', 'description' => 'W limit (median two pixel 1-sigma error) between restframe [1908.73-2799.117]'), 
 'psfmagerr_u' => array('type' => 'numeric', 'name' => 'uErr', 'description' => ''), 
 'twomass_sep' => array('type' => 'numeric', 'name' => '2MASS sep', 'description' => ''), 
 'psfmag_z' => array('type' => 'numeric', 'name' => 'z', 'description' => 'z PSF magnitude'), 
 'line_w_rest' => array('type' => 'numeric', 'name' => 'line Wrest', 'description' => 'Rest-frame equivalent width in Angstroms'), 
 'lat' => array('type' => 'numeric', 'name' => 'lat', 'description' => ''), 
 'a_u' => array('type' => 'numeric', 'name' => 'A_u', 'description' => ''), 
 'sys_lam_high' => array('type' => 'numeric', 'name' => 'sys lam high', 'description' => 'Upper wavelength limit of the SDSS spectrograph in Angstroms in the absorber rest frame'), 
 'ts_b_serendip' => array('type' => 'bool', 'name' => 'ts b serendip', 'description' => 'Serendipity target flag     0 = not targeted as serendipity  1 = targeted as serendipity'), 
 'line_ly_a' => array('type' => 'bool', 'name' => 'line in lya forest', 'description' => 'Flag indicating whether the line is shortward (1) or longward (0) of the Ly-a emission line'), 
 'field_best' => array('type' => 'numeric', 'name' => 'field best', 'description' => 'SDSS Frame Number'), 
 'lid' => array('type' => 'numeric', 'name' => 'lineId', 'description' => 'Absorption line number'), 
 'oldname_type' => array('type' => 'numeric', 'name' => 'oldname type', 'description' => 'Object Name Prefix if previously published. (SDSS in this column indicates that the object is a previously published SDSS discovery)'), 
 'ts_t_star' => array('type' => 'bool', 'name' => 'ts t star', 'description' => ''), 
 'qso_spec_avesnr_red' => array('type' => 'numeric', 'name' => 'qso spec avesnr red', 'description' => ''), 
 'qso_spec_medsnr_red' => array('type' => 'numeric', 'name' => 'qso spec medsnr red', 'description' => ''), 
 'deltaz' => array('type' => 'numeric', 'name' => 'deltaz', 'description' => 'Difference between the redshift of this particular line and the average redshift of the system into which it has been placed (z_line - z_avg)'), 
 'line_deltav' => array('type' => 'numeric', 'name' => 'line deltav', 'description' => 'Velocity difference; determined from deltaz'), 
 'psfmagerr_g' => array('type' => 'numeric', 'name' => 'gErr', 'description' => ''), 
 'firstmag' => array('type' => 'numeric', 'name' => 'first flux', 'description' => ''), 
 'camcol_best' => array('type' => 'numeric', 'name' => 'camcol best', 'description' => ''), 
 'w_obserr' => array('type' => 'numeric', 'name' => 'Wobserr', 'description' => '1-sigma error (in Angstroms) on the observer-frame equivalent width'), 
 'psfmag_g' => array('type' => 'numeric', 'name' => 'g', 'description' => 'g PSF magnitude'), 
 'first_sep' => array('type' => 'numeric', 'name' => 'first_sep', 'description' => ''), 
 'ts_t_hiz' => array('type' => 'bool', 'name' => 'ts t hiz', 'description' => ''), 
 'oldname_desig' => array('type' => 'numeric', 'name' => 'oldname desig', 'description' => ''), 
 'lat' => array('type' => 'numeric', 'name' => 'lat', 'description' => 'declination (degrees)'), 
 't_psfmag_i' => array('type' => 'numeric', 'name' => 't psfmag i', 'description' => ''), 
 'ts_b_first' => array('type' => 'bool', 'name' => 'ts b first', 'description' => ''), 
 'type' => array('type' => 'numeric', 'name' => 'type', 'description' => 'Selection method for identifying system - some combination of M;C; and F'), 
 'ts_b_lowz' => array('type' => 'bool', 'name' => 'ts b lowz', 'description' => 'Low-z Quasar (color selection only) target flag           0 = not targeted as low-z quasar        1 = targeted as low-z quasar'), 
 'psfmagerr_r' => array('type' => 'numeric', 'name' => 'rErr', 'description' => ''), 
 'objid' => array('type' => 'numeric', 'name' => 'objid', 'description' => ''), 
 'zab' => array('type' => 'numeric', 'name' => 'z (abs)', 'description' => ''), 
 'w_limit_1400_1549' => array('type' => 'numeric', 'name' => 'W limit 1400-1549', 'description' => 'W limit (median two pixel 1-sigma error) between restframe [1399.8-1549.48]'), 
 'aliasname' => array('type' => 'numeric', 'name' => 'aliasname', 'description' => ''), 
 'plate' => array('type' => 'numeric', 'name' => 'plate', 'description' => 'Spectroscopic plate number'), 
 'mjd' => array('type' => 'numeric', 'name' => 'mjd', 'description' => 'Spectroscopic MJD'), 
 'sdssname' => array('type' => 'numeric', 'name' => 'sdssname', 'description' => 'DR7 Object Designation   hhmmss.ss+ddmmss.s  (J2000; truncated coordinates)'), 
 'agg_line_snr' => array('type' => 'similar', 'name' => 'agg line snr', 'description' => ''), 
 'qso_spec_medsnr_red' => array('type' => 'numeric', 'name' => 'qso spec medsnr red', 'description' => '  Median per-pixel SNR of the spectrum at lambda>7200 Angstroms in the observed frame'), 
 'proj4text' => array('type' => 'numeric', 'name' => 'proj4text', 'description' => ''), 
 'bal_flag2' => array('type' => 'numeric', 'name' => 'BAL flag2', 'description' => 'Broad Absorption Line System QSO flag from Shen et al. DR7 BAL Catalog 0 = not identified as a BALQSO 1 = BAL identified in DR5 Gibson et al. catalog  2 = BAL candidate identified by Shen only  3 = BAL identified by Wesolowski only  4 = BAL candidate identified by both Shen and Wesolowski'), 
 'psfmagerr_u' => array('type' => 'numeric', 'name' => 'uErr', 'description' => 'error in u PSF magnitude'), 
 'target_first' => array('type' => 'numeric', 'name' => 'SDSSFIRST target flag', 'description' => 'SDSS FIRST target flag (Schneider et al. 2010)'), 
 'agg_line_ion_lam' => array('type' => 'similar', 'name' => 'agg line ion lam', 'description' => ''), 
 'rass_sep' => array('type' => 'numeric', 'name' => 'rass_sep', 'description' => ''), 
 't_psfmag_u' => array('type' => 'numeric', 'name' => 't psfmag u', 'description' => 'u PSF magnitude (TARGET)    0.000 ==> cannot retrieve value from SDSS database'), 
 'm_i' => array('type' => 'numeric', 'name' => 'M_i', 'description' => ''), 
 'mjd' => array('type' => 'numeric', 'name' => 'mjd', 'description' => ''), 
 'line_ion_name' => array('type' => 'numeric', 'name' => 'line ion name', 'description' => 'Name of species (e.g. Mg)'), 
 'flux_first' => array('type' => 'numeric', 'name' => 'flux first', 'description' => '20cm radio flux from FIRST (Schneider et al. 2010)'), 
 'fwhm' => array('type' => 'numeric', 'name' => 'fwhm', 'description' => 'FWHM of the line (pixels)'), 
 'ts_t_hiz' => array('type' => 'bool', 'name' => 'ts t hiz', 'description' => 'High-z Quasar (color selection only) target flag          0 = not targeted as high-z quasar       1 = targeted as high-z quasar'), 
 'agg_line_fwhm' => array('type' => 'similar', 'name' => 'agg line fwhm', 'description' => ''), 
 'twomassmagerr_k' => array('type' => 'numeric', 'name' => 'Kerr', 'description' => ''), 
 'mjd_best' => array('type' => 'numeric', 'name' => 'mjd best', 'description' => ''), 
 'mjd_best' => array('type' => 'numeric', 'name' => 'mjd best', 'description' => 'Modified Julian Date of imaging observation'), 
 't_psfmagerr_r' => array('type' => 'numeric', 'name' => 't psfmagerr r', 'description' => 'error in r PSF magnitude (TARGET)'), 
 'scienceprimary' => array('type' => 'numeric', 'name' => 'scienceprimary', 'description' => ''), 
 'ly_a' => array('type' => 'bool', 'name' => 'in lya forest', 'description' => 'Flag indicating whether the line is shortward (1) or longward (0) of the Ly-a emission line'), 
 'ion_name' => array('type' => 'numeric', 'name' => 'ion name', 'description' => 'Name of species (e.g. Mg)'), 
 'agg_ab_sys' => array('type' => 'similar', 'name' => 'agg_ab_sys', 'description' => ''), 
 't_psfmagerr_i' => array('type' => 'numeric', 'name' => 't psfmagerr i', 'description' => 'error in i PSF magnitude (TARGET)'), 
 'lgnh' => array('type' => 'numeric', 'name' => 'log[n_h]', 'description' => 'log [Galactic HI column density]'), 
 'z_fgal' => array('type' => 'numeric', 'name' => 'z fg gal', 'description' => 'Redshift of identified foreground galaxy'), 
 'qso_spec_avesnr_red' => array('type' => 'numeric', 'name' => 'qso spec avesnr red', 'description' => 'Mean per-pixel SNR of the spectrum at lambda>7200 Angstroms in the observed frame'), 
 'mjd' => array('type' => 'numeric', 'name' => 'mjd', 'description' => 'Modified Julian Date of spectroscopic observation'), 
 'qso_z_best' => array('type' => 'numeric', 'name' => 'qso z best', 'description' => 'Best determined emission redshift, used by the pipeline (from Hewett & Wild 2010, if available)'), 
 'field_best' => array('type' => 'numeric', 'name' => 'field best', 'description' => ''), 
 'twomass_sep' => array('type' => 'numeric', 'name' => '2MASS sep', 'description' => 'SDSS/2MASS separation (arc seconds)'), 
 't_psfmag_z' => array('type' => 'numeric', 'name' => 't psfmag z', 'description' => 'z PSF magnitude (TARGET)'), 
 'bestprimtarget' => array('type' => 'bool', 'name' => 'bestprimtarget', 'description' => 'Target selection flag (BEST)'), 
 't_psfmagerr_u' => array('type' => 'numeric', 'name' => 't psfmagerr u', 'description' => 'error in u PSF magnitude (TARGET)'), 
 'sys_lam_high' => array('type' => 'numeric', 'name' => 'sys lam high', 'description' => ''), 
 'w_limit_1216_1241' => array('type' => 'numeric', 'name' => 'W limit 1216-1241', 'description' => 'W limit (median two pixel 1-sigma error) between restframe [1215.7-1240.81'), 
 'twomass_flag' => array('type' => 'numeric', 'name' => '2MASS flag', 'description' => '2MASS Flag = 9*JFLAG+3*HFLAG+KFLAG  Individual filter flags   0 = No Detection   1 = Catalog Match  2 = New Photometry on Images'), 
 'psfmag_r' => array('type' => 'numeric', 'name' => 'r', 'description' => ''), 
 'snr' => array('type' => 'numeric', 'name' => 'snr', 'description' => 'Significance of the line in standard deviations from the error (i.e.; W_obs / W_obs_err)'), 
 'qso_bal_flag2' => array('type' => 'numeric', 'name' => 'qso bal flag2', 'description' => ''), 
 'qso_w_limit_1909_2799' => array('type' => 'numeric', 'name' => 'qso W limit 1909-2799', 'description' => ''), 
 'formtype' => array('type' => 'numeric', 'name' => 'formtype', 'description' => ''), 
 'rass_sn' => array('type' => 'numeric', 'name' => 'rass_sn', 'description' => ''), 
 'specid' => array('type' => 'numeric', 'name' => 'specid', 'description' => 'Spectroscopic id (primary key)'), 
 'agg_line_deltav' => array('type' => 'similar', 'name' => 'agg line deltav', 'description' => ''), 
 't_psfmag_i' => array('type' => 'numeric', 'name' => 't psfmag i', 'description' => 'i PSF magnitude (TARGET)'), 
 'ts_t_lowz' => array('type' => 'bool', 'name' => 'ts t lowz', 'description' => 'Low-z Quasar (color selection only) target flag           0 = not targeted as low-z quasar        1 = targeted as low-z quasar'), 
 'ts_t_gal' => array('type' => 'bool', 'name' => 'ts t gal', 'description' => ''), 
 'twomassmag_h' => array('type' => 'numeric', 'name' => 'H', 'description' => '2MASS H magnitude'), 
 't_psfmag_r' => array('type' => 'numeric', 'name' => 't psfmag r', 'description' => 'r PSF magnitude (TARGET)'), 
 'ts_t_first' => array('type' => 'bool', 'name' => 'ts t first', 'description' => ''), 
 'srid' => array('type' => 'numeric', 'name' => 'srid', 'description' => ''), 
 'qso_w_limit_1400_1549' => array('type' => 'numeric', 'name' => 'qso W limit 1400-1549', 'description' => ''), 
 'mode' => array('type' => 'numeric', 'name' => 'mode', 'description' => 'SDSS MODE flag (blends, overlapping scans)    1 = Primary object      2 = Secondary observation      3 = Family observation'), 
 'sdssname' => array('type' => 'numeric', 'name' => 'sdssname', 'description' => ''), 
 'agg_line_w_obserr' => array('type' => 'similar', 'name' => 'agg line Wobserr', 'description' => ''), 
 'qso_spec_avesnr' => array('type' => 'numeric', 'name' => 'qso spec avesnr', 'description' => ''), 
 'psfmagerr_i' => array('type' => 'numeric', 'name' => 'iErr', 'description' => 'i PSF magnitude error'), 
 't_psfmag_r' => array('type' => 'numeric', 'name' => 't psfmag r', 'description' => ''), 
 'obj_best' => array('type' => 'numeric', 'name' => 'obj best', 'description' => 'SDSS Object Number'), 
 'ts_t_serendip' => array('type' => 'bool', 'name' => 'ts t serendip', 'description' => ''), 
 'qso_z_fgal' => array('type' => 'numeric', 'name' => 'qso z fgal', 'description' => ''), 
 'qid' => array('type' => 'numeric', 'name' => 'QSOId', 'description' => ''), 
 'delgi' => array('type' => 'numeric', 'name' => 'delta(g-i)', 'description' => ''), 
 'sys_grade' => array('type' => 'numeric', 'name' => 'sys grade', 'description' => ''), 
 'auth_name' => array('type' => 'numeric', 'name' => 'auth_name', 'description' => ''), 
 'columnname' => array('type' => 'numeric', 'name' => 'columnname', 'description' => ''), 
 'lg_rass_rate' => array('type' => 'numeric', 'name' => 'lg_rass_rate', 'description' => ''), 
 'w_limit_1241_1400' => array('type' => 'numeric', 'name' => 'W limit 1241-1400', 'description' => 'W limit (median two pixel 1-sigma error) between restframe [1240.81-1399.8]'), 
 'uniform' => array('type' => 'numeric', 'name' => 'uniform', 'description' => ''), 
 'psfmag_i' => array('type' => 'numeric', 'name' => 'i', 'description' => 'i PSF magnitude'), 
 'qso_imag' => array('type' => 'numeric', 'name' => 'qso imag', 'description' => ''), 
 'fiber' => array('type' => 'numeric', 'name' => 'fiber', 'description' => 'Spectroscopic Fiber Number'), 
 'ts_t_rosat' => array('type' => 'bool', 'name' => 'ts t rosat', 'description' => 'ROSAT target flag           0 = not targeted as ROSAT        1 = targeted as ROSAT'), 
 'twomassmagerr_h' => array('type' => 'numeric', 'name' => 'Herr', 'description' => ''), 
 'ts_t_rosat' => array('type' => 'bool', 'name' => 'ts t rosat', 'description' => ''), 
 'line_w_resterr' => array('type' => 'numeric', 'name' => 'line Wresterr', 'description' => '1-sigma error (in Angstroms) rest-frame equivalent width'), 
 'twomassmagerr_j' => array('type' => 'numeric', 'name' => 'Jerr', 'description' => ''), 
 'psfmagerr_r' => array('type' => 'numeric', 'name' => 'rErr', 'description' => 'r PSF magnitude error'), 
 'plate' => array('type' => 'numeric', 'name' => 'plate', 'description' => ''), 
 't_psfmagerr_z' => array('type' => 'numeric', 'name' => 't psfmagerr z', 'description' => ''), 
 'iabmag' => array('type' => 'numeric', 'name' => 'M_i', 'description' => 'Absolute magnitude in the i-band (Schneider et al. 2010)'), 
 'line_snr' => array('type' => 'numeric', 'name' => 'line snr', 'description' => 'Significance of the line in standard deviations from the error (i.e.; W_obs / W_obs_err)'), 
 'geopoint' => array('type' => 'numeric', 'name' => 'geopoint', 'description' => 'Binary representaion of lon/lat for spatial queries'), 
 'rass_sn' => array('type' => 'numeric', 'name' => 'rass_sn', 'description' => 'S/N ratio for RASS count rate'), 
 'run_best' => array('type' => 'numeric', 'name' => 'run best', 'description' => 'SDSS Imaging Run Number for photometric measurements'), 
 'rerun_best' => array('type' => 'numeric', 'name' => 'rerun best', 'description' => ''), 
 'line_obs_lam' => array('type' => 'numeric', 'name' => 'line obs lam', 'description' => 'Observed Wavelength: observed wavelength of the absorption line in Angstroms'), 
 'agg_line_w_resterr' => array('type' => 'similar', 'name' => 'agg line W resterr', 'description' => ''), 
 'ts_b_lowz' => array('type' => 'bool', 'name' => 'ts b lowz', 'description' => ''), 
 't_psfmag_u' => array('type' => 'numeric', 'name' => 't psfmag u', 'description' => ''), 
 'line_deltaz' => array('type' => 'numeric', 'name' => 'line deltaz', 'description' => 'Difference between the redshift of this particular line and the average redshift of the system into which it has been placed (z_line - z_avg)'), 
 'snr_first' => array('type' => 'numeric', 'name' => 'snr first', 'description' => '20cm radio flux signal-to-noise from FIRST (Schneider et al. 2010)'), 
 'objid' => array('type' => 'numeric', 'name' => 'objid', 'description' => 'BestObjID (64-bit integer)'), 
 'firstmag' => array('type' => 'numeric', 'name' => 'first flux', 'description' => 'FIRST Peak flux density (AB mag) at 20 cm  (AB mag = -2.5 log_10 [f_nu / 3631 Jy])     0.000 ==> no detection    -1.000 ==> not in FIRST survey area'), 
 'ts_b_first' => array('type' => 'bool', 'name' => 'ts b first', 'description' => 'FIRST target flag           0 = not targeted as FIRST        1 = targeted as FIRST'), 
 'ts_b_rosat' => array('type' => 'bool', 'name' => 'ts b rosat', 'description' => ''), 
 't_psfmagerr_g' => array('type' => 'numeric', 'name' => 't psfmagerr g', 'description' => 'error in g PSF magnitude (TARGET)'), 
 'spec_medsnr_red' => array('type' => 'numeric', 'name' => 'spec median SNR red', 'description' => '  Median per-pixel SNR of the spectrum at lambda>7200 Angstroms in the observed frame'), 
 'qso_spec_medsnr' => array('type' => 'numeric', 'name' => 'qso spec medsnr', 'description' => ''), 
 'beta' => array('type' => 'numeric', 'name' => 'beta', 'description' => 'Velocity (v/c) of the absorber in the QSO rest-frame; calculated using Hewett & Wild 2010 redshifts'), 
 'lam_high' => array('type' => 'numeric', 'name' => 'lam high', 'description' => 'Upper wavelength limit of the SDSS spectrograph in Angstroms in the absorber rest frame'), 
 'qso_z_best' => array('type' => 'numeric', 'name' => 'qso z best', 'description' => ''), 
 'w_obs' => array('type' => 'numeric', 'name' => 'Wobs', 'description' => 'Observer-frame equivalent width in Angstroms as determined by fitting a Gaussian profile to the absorption line'), 
 );
 $tables = array('cat_sys' => 'Systems', 'cat_line' => 'Lines', 'cat_qso' => 'Quasars', 'cat_join_all_mv' => 'Join Table (All)', 'cat_join' => 'Join Table'); 
$table_attributes = array(
'cat_sys' => array('all' => array('qid', 'sid', 'zab', 'lam_low', 'lam_high', 'grade', 'type', 'beta', )), 
'cat_line' => array('all' => array('qid', 'sid', 'lid', 'obs_lam', 'w_obs', 'w_obserr', 'ion_lam', 'ion_name', 'ly_a', 'deltaz', 'deltav', 'snr', 'fwhm', )), 
'cat_qso' => array('all' => array('qid', 'plate', 'fiber', 'mjd', 'z_s10', 'z_best', 'imag', 'bal_flag', 'bal_flag2', 'flux_first', 'snr_first', 'target_first', 'sep_first', 'iabmag', 'z_fgal', 'spec_avesnr', 'spec_medsnr', 'spec_avesnr_red', 'spec_medsnr_red', 'w_limit_1216_1241', 'w_limit_1241_1400', 'w_limit_1400_1549', 'w_limit_1549_1909', 'w_limit_1909_2799', 'w_limit_2799_3969', 'w_limit_3969_8200', 'specid', 'agg_ab_sys', )), 
'cat_join_all_mv' => array('all' => array('specid', 'sdssname', 'ra', 'decl', 'redshift', 'psfmag_u', 'psfmagerr_u', 'psfmag_g', 'psfmagerr_g', 'psfmag_r', 'psfmagerr_r', 'psfmag_i', 'psfmagerr_i', 'psfmag_z', 'psfmagerr_z', 'a_u', 'lgnh', 'firstmag', 'first_sn', 'first_sep', 'lg_rass_rate', 'rass_sn', 'rass_sep', 'twomassmag_j', 'twomassmagerr_j', 'twomassmag_h', 'twomassmagerr_h', 'twomassmag_k', 'twomassmagerr_k', 'twomass_sep', 'twomass_flag', 'm_i', 'delgi', 'morphology', 'scienceprimary', 'mode', 'uniform', 'bestprimtarget', 'ts_b_lowz', 'ts_b_hiz', 'ts_b_first', 'ts_b_rosat', 'ts_b_serendip', 'ts_b_star', 'ts_b_gal', 'run_best', 'mjd_best', 'mjd', 'plate', 'fiber', 'rerun_best', 'camcol_best', 'field_best', 'obj_best', 'targprimtarget', 'ts_t_lowz', 'ts_t_hiz', 'ts_t_first', 'ts_t_rosat', 'ts_t_serendip', 'ts_t_star', 'ts_t_gal', 't_psfmag_u', 't_psfmagerr_u', 't_psfmag_g', 't_psfmagerr_g', 't_psfmag_r', 't_psfmagerr_r', 't_psfmag_i', 't_psfmagerr_i', 't_psfmag_z', 't_psfmagerr_z', 'objid', 'oldname_type', 'oldname_desig', 'lon', 'lat', 'geopoint', 'qid', 'qso_z_best', 'qso_imag', 'qso_bal_flag', 'qso_bal_flag2', 'qso_z_fgal', 'qso_spec_avesnr', 'qso_spec_medsnr', 'qso_spec_avesnr_red', 'qso_spec_medsnr_red', 'qso_w_limit_1216_1241', 'qso_w_limit_1241_1400', 'qso_w_limit_1400_1549', 'qso_w_limit_1549_1909', 'qso_w_limit_1909_2799', 'qso_w_limit_2799_3969', 'qso_w_limit_3969_8200', 'sid', 'sys_zab', 'sys_lam_low', 'sys_lam_high', 'sys_grade', 'sys_type', 'sys_beta', 'lid', 'line_obs_lam', 'line_w_obs', 'line_w_obserr', 'line_w_rest', 'line_w_resterr', 'line_ion_lam', 'line_ion_name', 'line_ly_a', 'line_deltaz', 'line_deltav', 'line_snr', 'line_fwhm', 'qso_agg_ab_sys', )), 
'cat_join' => array('all' => array()), 
);
?>